import Head from "next/head";
import Link from "next/link";

const LearnLanguage = ({ listOfLanguages }) => {
    const listL = listOfLanguages.map((e) => {
        return (
            <li>
                <Link href={`/learn/${e.toLowerCase()}`}>
                    {e[0].toUpperCase() + e.substring(1)}
                </Link>
            </li>
        );
    });
    return (
        <>
            <Head>
                <title>Learn | Taalimu</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Select language to learn</h1>
            <ul>{listL}</ul>
        </>
    );
};

LearnLanguage.defaultProps = {
    listOfLanguages: ["Swahili", "Luo", "Kikuyu", "Kalenjin"],
};
export default LearnLanguage;
