import { website_title } from "@/constants/constant";
import Head from "next/head";
import { useRouter } from "next/router";

const CulturePage = () => {
    const router = useRouter()
    const {culture} = router.query
    const capitalizeCulture = culture[0].toUpperCase() + culture.substring(1)
    return (
        <>
            <Head>
                <title>The {capitalizeCulture} | {website_title}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Single language page</h1>
        </>
    );
};

export default CulturePage;
