import { website_title } from "@/constants/constant";
import Head from "next/head";
import { useRouter } from "next/router";

const EthnicGroupPage = () => {
    const router = useRouter()
    const {ethnicGroup} = router.query
    // const capGroup = ethnicGroup[0].toUpperCase() + ethnicGroup.substring(1)

    return (
        <>
            {" "}
            <Head>
                <title>
                    The {ethnicGroup} | {website_title}
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>the {ethnicGroup}</h1>
        </>
    );
};

export default EthnicGroupPage;
