import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import MainLayout from "@/layouts/Main";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <MainLayout>
            <Head>
                <title>Taalimu</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>Welcome ma nigga</h1>
            </main>
        </MainLayout>
    );
}
